# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xcvu095-ffva2104-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/users/kfujita/resol_hdl/segment/proj/segment_1/segment_1.cache/wt [current_project]
set_property parent.project_path /home/users/kfujita/resol_hdl/segment/proj/segment_1/segment_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/users/kfujita/resol_hdl/segment/proj/segment_1/segment_1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  /home/users/kfujita/resol_hdl/segment/src/conv_one.v
  /home/users/kfujita/resol_hdl/segment/src/common/delay.v
  /home/users/kfujita/resol_hdl/segment/src/extnet.v
  /home/users/kfujita/resol_hdl/segment/src/common/fifo.v
  /home/users/kfujita/resol_hdl/segment/src/common/forward.v
  /home/users/kfujita/resol_hdl/segment/src/common/integrate.v
  /home/users/kfujita/resol_hdl/segment/src/itgnet.v
  /home/users/kfujita/resol_hdl/segment/src/layer.v
  /home/users/kfujita/resol_hdl/segment/src/maxpoolng.v
  /home/users/kfujita/resol_hdl/segment/src/common/ram.v
  /home/users/kfujita/resol_hdl/segment/src/rdcnet.v
  /home/users/kfujita/resol_hdl/segment/src/common/stream_patch.v
  /home/users/kfujita/resol_hdl/segment/src/unpooling.v
  /home/users/kfujita/resol_hdl/segment/src/top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/users/kfujita/resol_hdl/segment/xdc/vcu108.xdc
set_property used_in_implementation false [get_files /home/users/kfujita/resol_hdl/segment/xdc/vcu108.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top -part xcvu095-ffva2104-2-e -max_dsp 768 -max_bram_cascade_height 3456


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
